<a href="https://colab.research.google.com/github/santaceciliahustler/Senai_fullstack/blob/main/Aula_2_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
set1 = {'Sorocaba','São Paulo','São Roque','Piedade','Campinas'}
set2 = {'São Paulo','Guarulhos', 'Guarulhos', 'Osasco'}

In [ ]:
set1

{'Campinas', 'Piedade', 'Sorocaba', 'São Paulo', 'São Roque'}

In [ ]:
set2

{'Guarulhos', 'Osasco', 'São Paulo'}

set nao aceita duplicidade

In [ ]:
set1.union(set2)

{'Campinas',
 'Guarulhos',
 'Osasco',
 'Piedade',
 'Sorocaba',
 'São Paulo',
 'São Roque'}

In [ ]:
set2.difference(set1)

{'Guarulhos', 'Osasco'}

In [ ]:
set2.intersection(set1)


{'São Paulo'}

In [ ]:
set2.add('Suzano')

In [ ]:
set2

{'Guarulhos', 'Osasco', 'Suzano', 'São Paulo'}

In [ ]:
set2.remove('Osasco')

In [ ]:
set2

{'Guarulhos', 'Suzano', 'São Paulo'}

In [ ]:
dict1={'Nome':'Jhean',
       "Idade": 34,
       'Cidade': 'São Paulo',
       'Profissão': 'Economista'}


In [ ]:
dict1

{'Cidade': 'São Paulo',
 'Idade': 34,
 'Nome': 'Jhean',
 'Profissão': 'Economista'}

In [ ]:
dict1['Nome']

'Jhean'

In [ ]:
dict2 = {'Cidade': ['São Paulo','Sorocaba'],
 'Idade': [34,28],
 'Nome': ['Jhean','Raphael'],
 'Profissão': ['Economista','Geografo']}

In [ ]:
dict2

{'Cidade': ['São Paulo', 'Sorocaba'],
 'Idade': [34, 28],
 'Nome': ['Jhean', 'Raphael'],
 'Profissão': ['Economista', 'Geografo']}

In [ ]:
dict2['Nome']

['Jhean', 'Raphael']

In [ ]:
type(dict2)

dict

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
arr1=np.array([1,2,3,4])
arr1
arr1[0]

1

In [ ]:
arr2=np.array([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12],
               [13,14,15,16]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
series1 =pd.Series(arr1, index =[2000,2001,2002,2003])
series1[2003]


4

In [ ]:
data1= pd.DataFrame(dict2)
data1

Cidade  Idade     Nome   Profissão
0  São Paulo     34    Jhean  Economista
1   Sorocaba     28  Raphael    Geografo

In [ ]:
a=100
b=20
if(a<100):
  print('Tudo ok')
else:
    print('NOK')

NOK


python identifica pela identação

In [ ]:
a=-1
b=20
if(a>=100):
  print('Tudo ok')
elif(a>=80):
  print('Vixi, ai é ruim')
elif(a>=60):
  print('Não to gostando')
elif(a>=40):
  print:('Vixi Maria')
elif(a>=20):
  print('Segure as pontas')
elif(a>=0):
  print('EITAAAA')
else:
    print('lascou')

lascou


In [ ]:
a=1
b=2
a==a


True

In [ ]:
a==b

False

In [ ]:
(a==a) & (a!=b)

True

In [ ]:
True & True

True

In [ ]:
True & False

False

In [ ]:
False & True

False

In [ ]:
False & False

False

In [4]:
for i in range (10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [12]:
n=0
while n <= 10:
  print (n)
  n+=1

0
1
2
3
4
5
6
7
8
9
10


In [24]:

for i in range (2,10):
  if i==5:
    pass
  else:
    print(i)

2
3
4
6
7
8
9


if nao pode ter um if vazio

In [32]:
def juros (i,n,P):
  if i>=1:
      print('O valor da taxa de juros não pode ser superior a 1')
  else:
    juros = P*(1+i)**n
    return(juros)

In [34]:
juros(i=.10, n=2,P=100)

121.00000000000001

In [38]:
def media(x):
  if(len(x)==0):
    print('Não podemos fazer média de um conjunto vazio')
    exit
  else:
      x= list(x)
      med=sum(x)/len(x)
      return med

In [47]:
media(x=[0,1,2,3])

1.5

In [46]:
media(x=[])

Não podemos fazer média de um conjunto vazio


In [49]:
a=[0,2,3,4]

In [51]:
(max(a)-min(a))/max(a)

1.0

In [58]:
import numpy as np
def normalizador(x):
  calc=np.array(x)
  norm=(calc.max() - calc)/calc.max()
  return norm

In [59]:
normalizador(np.arange(15))

array([1.        , 0.92857143, 0.85714286, 0.78571429, 0.71428571,
       0.64285714, 0.57142857, 0.5       , 0.42857143, 0.35714286,
       0.28571429, 0.21428571, 0.14285714, 0.07142857, 0.        ])

In [63]:
def desvio_padrao(x):
  med=media(x)
  desv=sum(x-media(x))

In [87]:
x=[0,1,2,3,4,4,5,6,7,7,8,9,10,13,14,15,10,15]
x=np.array(x)

In [91]:
(sum((x-media(x))**2)/(len(x)-1))**0.5

4.742038391301272

In [109]:
def varianca(x):
  x=np.array(x)
  var=sum((x-media(x))**2)/(len(x)-1)
  return var

In [111]:
def desvio(x):
  desvio= varianca(x)**0.5
  return(desvio)

In [115]:
desvio([0,1,2,5,6,7,10,12,13,15,19])

6.145212475060269

In [116]:
i=.10
n=np.arange(0,20)
P=100

In [117]:
P*(1+i)**n

array([100.        , 110.        , 121.        , 133.1       ,
       146.41      , 161.051     , 177.1561    , 194.87171   ,
       214.358881  , 235.7947691 , 259.37424601, 285.31167061,
       313.84283767, 345.22712144, 379.74983358, 417.72481694,
       459.49729864, 505.4470285 , 555.99173135, 611.59090448])

In [127]:
pmt = 1500
i=.05
n=np.arange(20)


In [128]:
pmt*20

30000

In [129]:
pmt/((1+i)**n)

array([1500.        , 1428.57142857, 1360.54421769, 1295.7563978 ,
       1234.05371219, 1175.2892497 , 1119.32309495, 1066.0219952 ,
       1015.25904304,  966.91337433,  920.86988031,  877.01893363,
        835.25612727,  795.48202597,  757.60192949,  721.52564714,
        687.16728299,  654.44503142,  623.2809823 ,  593.60093552])

In [130]:
sum(pmt/((1+i)**n))

19627.98128950047

In [131]:
pmt*20-sum(pmt/((1+i)**n))

10372.018710499531